{% set name = "fastuuid" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 178947fc2f995b38497a74172adee64fdeb8b7ec18f2a5934d037641ba265d26

build:
  number: 0
  skip: true  # [py<38]
  script_env:
    - PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - maturin >=1.0,<2.0
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - maturin >=1.0,<2.0
  run:
    - python

# ModuleNotFoundError: No module named 'uuid_extensions'
{% set ignore_tests = "--ignore=tests/test_benchmarks.py" %}

test:
  source_files:
    - tests
  imports:
    - fastuuid
  requires:
    - pip
    - pytest
    - hypothesis
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }}

about:
  home: https://github.com/fastuuid/fastuuid
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Python bindings to Rust's UUID library
  description: Python bindings to Rust's UUID library
  doc_url: https://github.com/fastuuid/fastuuid
  dev_url: https://github.com/fastuuid/fastuuid

extra:
  recipe-maintainers:
    - jan-janssen
